import type { Metadata } from 'next';
import { Roboto, Geist } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/providers/ReduxProvider';
import NextThemeProvider from '../context/Theme';
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const roboto = Roboto({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Auto Wizard',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", geist.variable)}>
      <body className={` ${roboto.className} antialiased`}>
        <NextThemeProvider
          defaultTheme="system"
          attribute="class"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>{children}</ReduxProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
