import type { Metadata } from 'next';
import { Roboto, Geist } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/providers/ReduxProvider';
import NextThemeProvider from '../context/Theme';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/sonner';
import { auth } from 'auth';
import { SessionProvider } from 'next-auth/react';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const roboto = Roboto({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Auto Wizard',
  description: 'Generated by create next app',
};

async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning className={cn('font-sans', geist.variable)}>
      <SessionProvider session={session}>
        <body className={` ${roboto.className} antialiased`}>
          <NextThemeProvider
            defaultTheme="system"
            attribute="class"
            enableSystem
            disableTransitionOnChange
          >
            <ReduxProvider>{children}</ReduxProvider>
          </NextThemeProvider>
          <Toaster />
        </body>
      </SessionProvider>
    </html>
  );
}
export default Layout;
